/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 *
 * ⚠️ 生成自官方 api_bundle.yaml（v1），与 2026-08-05 实测存在差异，参考时注意：
 * 1. 官方 spec 未描述响应包裹层 { errors, data, success }——业务数据需解包 data，错误取 errors[0].msg；
 * 2. voc_id 实际格式为 "voc-" 前缀长串，与 spec 示例不同；
 * 3. GET /memo/notepads 的 limit 实际上限为 10；
 * 4. 记忆卡端点需要 Markji Plus 权限、内容写接口需要写权限（403）。
 * 业务代码的类型入口仍以 src/lib/apiClient.ts 手写类型为准（已按实测修正）。
 * 重新生成：node node_modules/openapi-typescript/bin/cli.js api_bundle.yaml -o src/types/momo-openapi.ts
 */

export interface paths {
    "/api/v1/markji/decks/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取文件夹列表 */
        get: operations["maimemo.openapi.markji.v1.MarkjiContentService.ListFolders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/markji/decks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取我的牌组列表 */
        get: operations["maimemo.openapi.markji.v1.MarkjiContentService.ListDecks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/markji/decks/{deck}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取牌组信息 */
        get: operations["maimemo.openapi.markji.v1.MarkjiContentService.GetDeck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/markji/decks/{deck}/chapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取牌组章节 */
        get: operations["maimemo.openapi.markji.v1.MarkjiContentService.ListChapters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/markji/decks/{deck}/chapters/{chapter}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取指定章节 */
        get: operations["maimemo.openapi.markji.v1.MarkjiContentService.GetChapter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/markji/decks/{deck}/cards/{card}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取卡片 */
        get: operations["maimemo.openapi.markji.v1.MarkjiContentService.GetCard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/markji/decks/{deck}/chapters/{chapter}/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 新建卡片 */
        post: operations["maimemo.openapi.markji.v1.MarkjiContentService.CreateCard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/markji/decks/{deck_id}/cards/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 更新卡片 */
        post: operations["maimemo.openapi.markji.v1.MarkjiContentService.UpdateCard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/markji/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 上传文件
         * @description multipart/form-data 请求，文件字段名为 `file`
         */
        post: operations["maimemo.openapi.markji.v1.MarkjiContentService.UploadFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/markji/files/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 查询文件 */
        post: operations["maimemo.openapi.markji.v1.MarkjiContentService.QueryFiles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memo/interpretations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取释义
         * @description 获取单词下自己创建的释义
         */
        get: operations["maimemo.openapi.memo.interpretation.v1.InterpretationService.ListInterpretations"];
        put?: never;
        /** 创建释义 */
        post: operations["maimemo.openapi.memo.interpretation.v1.InterpretationService.CreateInterpretation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memo/interpretations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 更新释义 */
        post: operations["maimemo.openapi.memo.interpretation.v1.InterpretationService.UpdateInterpretation"];
        /** 删除释义 */
        delete: operations["maimemo.openapi.memo.interpretation.v1.InterpretationService.DeleteInterpretation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memo/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取助记
         * @description 获取单词下自己创建的助记
         */
        get: operations["maimemo.openapi.memo.note.v1.NoteService.ListNotes"];
        put?: never;
        /** 创建助记 */
        post: operations["maimemo.openapi.memo.note.v1.NoteService.CreateNote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memo/notes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 更新助记 */
        post: operations["maimemo.openapi.memo.note.v1.NoteService.UpdateNote"];
        /** 删除助记 */
        delete: operations["maimemo.openapi.memo.note.v1.NoteService.DeleteNote"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memo/notepads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询云词本 */
        get: operations["maimemo.openapi.memo.notepad.v1.NotepadService.ListNotepads"];
        put?: never;
        /** 创建云词本 */
        post: operations["maimemo.openapi.memo.notepad.v1.NotepadService.CreateNotepad"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memo/notepads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取云词本 */
        get: operations["maimemo.openapi.memo.notepad.v1.NotepadService.GetNotepad"];
        put?: never;
        /** 更新云词本 */
        post: operations["maimemo.openapi.memo.notepad.v1.NotepadService.UpdateNotepad"];
        /** 删除云词本 */
        delete: operations["maimemo.openapi.memo.notepad.v1.NotepadService.DeleteNotepad"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memo/phrases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取例句
         * @description 获取单词下自己创建的例句
         */
        get: operations["maimemo.openapi.memo.phrase.v1.PhraseService.ListPhrases"];
        put?: never;
        /** 创建例句 */
        post: operations["maimemo.openapi.memo.phrase.v1.PhraseService.CreatePhrase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memo/phrases/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 更新例句 */
        post: operations["maimemo.openapi.memo.phrase.v1.PhraseService.UpdatePhrase"];
        /** 删除例句 */
        delete: operations["maimemo.openapi.memo.phrase.v1.PhraseService.DeletePhrase"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memo/study/get_study_progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 获取今日学习进度（公测）
         * @description 如果当日未打开 App 进行初始化则无法准确计算总数
         *       \
         *       \
         *     <b>公测期间不保证可用性和可能会随时调整，需要在 App 中开启自动同步</b>
         */
        post: operations["maimemo.openapi.memo.study.v1.StudyService.GetStudyProgress"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memo/study/get_today_items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 获取今日学习单词（公测）
         * @description 如果当日未打开 App 进行初始化则无法获取
         *       \
         *       \
         *     <b>公测期间不保证可用性和可能会随时调整，需要在 App 中开启自动同步</b>
         */
        post: operations["maimemo.openapi.memo.study.v1.StudyService.GetTodayItems"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memo/study/query_study_records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 查询学习记录（公测）
         * @description 查询场景举例
         *     - 获取规划总量：`as_count=true`
         *     - 获取未来某天要背的单词数：`next_study_date: {end: "2026-04-01T00:00:00+08:00"}, as_count=true`
         *     - 获取未来某天要背的单词列表：`next_study_date: {end: "2026-04-01T00:00:00+08:00"}`
         *
         *       \
         *     <b>公测期间不保证可用性和可能会随时调整，需要在 App 中开启自动同步</b>
         */
        post: operations["maimemo.openapi.memo.study.v1.StudyService.QueryStudyRecords"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memo/study/add_words": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 添加单词（公测）
         * @description
         *     <b>公测期间不保证可用性和可能会随时调整，需要在 App 中开启自动同步</b>
         */
        post: operations["maimemo.openapi.memo.study.v1.StudyService.AddWords"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memo/study/advance_study": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 提前复习（公测）
         * @description 将单词提前到当下马上复习，需要升级到 10 级解锁提前复习功能
         *
         *     <b>公测期间不保证可用性和可能会随时调整，需要在 App 中开启自动同步</b>
         */
        post: operations["maimemo.openapi.memo.study.v1.StudyService.AdvanceStudy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memo/vocabulary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取单词 */
        get: operations["maimemo.openapi.memo.vocabulary.v1.VocabularyService.GetVocabulary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memo/vocabulary/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 查询单词
         * @description 查询条件互斥，只能生效一个
         */
        post: operations["maimemo.openapi.memo.vocabulary.v1.VocabularyService.ListVocabulary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description 墨墨记忆卡资源来源
         *
         *     - `SELF`: 自建
         *     - `FORK`: 派生
         * @enum {string}
         */
        MarkjiSource: "SELF" | "FORK";
        /**
         * @description 墨墨记忆卡资源状态
         *
         *     - `NORMAL`: 正常
         *     - `DELETED`: 删除
         *     - `BLOCKED`: 封禁
         * @enum {string}
         */
        MarkjiStatus: "NORMAL" | "DELETED" | "BLOCKED";
        /**
         * @description 墨墨记忆卡内容类型
         *
         *     - `PLAIN`: 纯文本
         * @enum {string}
         */
        MarkjiContentType: "PLAIN";
        /**
         * @description 文件夹内对象类型
         *
         *     - `FOLDER`: 文件夹
         *     - `DECK`: 牌组
         * @enum {string}
         */
        MarkjiFolderItemClass: "FOLDER" | "DECK";
        /** @description 暂无文档 */
        MarkjiRootDeck: {
            /**
             * @description 牌组 OpenAPI ID
             * @example null
             */
            id: string;
            /**
             * @description 上游牌组 OpenAPI ID
             * @example null
             */
            parent_id?: string;
            /** @description 牌组来源<br><br>引用自：[MarkjiSource](/schemas/MarkjiSource) */
            source: components["schemas"]["MarkjiSource"];
            /** @description 牌组状态<br><br>引用自：[MarkjiStatus](/schemas/MarkjiStatus) */
            status: components["schemas"]["MarkjiStatus"];
            /**
             * @description 牌组名称
             * @example null
             */
            name: string;
            /**
             * @description 牌组简介
             * @example null
             */
            description: string;
            /**
             * @description 用户 OpenAPI ID
             * @example null
             */
            creator: string;
            /**
             * @description 用户 OpenAPI ID 列表
             * @example null
             */
            authors: string[];
            /**
             * @description 牌组版本
             * @example null
             */
            revision: number;
            /**
             * @description 是否私有
             * @example false
             */
            is_private: boolean;
            /**
             * @description 卡片数量
             * @example null
             */
            card_count: number;
            /**
             * @description 章节数量
             * @example null
             */
            chapter_count: number;
            /**
             * Format: ISODate
             * @description 创建时间
             * @example 2021-07-09T00:16:00.000Z
             */
            created_time: string;
            /**
             * Format: ISODate
             * @description 更新时间
             * @example 2021-07-09T00:16:00.000Z
             */
            updated_time: string;
        };
        /** @description 暂无文档 */
        MarkjiDeck: {
            /**
             * @description 牌组 OpenAPI ID
             * @example null
             */
            id: string;
            /**
             * @description 上游牌组 OpenAPI ID
             * @example null
             */
            parent_id?: string;
            /** @description 牌组来源<br><br>引用自：[MarkjiSource](/schemas/MarkjiSource) */
            source: components["schemas"]["MarkjiSource"];
            /** @description 牌组状态<br><br>引用自：[MarkjiStatus](/schemas/MarkjiStatus) */
            status: components["schemas"]["MarkjiStatus"];
            /**
             * @description 牌组名称
             * @example null
             */
            name: string;
            /**
             * @description 牌组简介
             * @example null
             */
            description: string;
            /**
             * @description 用户 OpenAPI ID
             * @example null
             */
            creator: string;
            /**
             * @description 用户 OpenAPI ID 列表
             * @example null
             */
            authors: string[];
            /**
             * @description 牌组版本
             * @example null
             */
            revision: number;
            /**
             * @description 是否私有
             * @example false
             */
            is_private: boolean;
            /**
             * @description 卡片数量
             * @example null
             */
            card_count: number;
            /**
             * @description 章节数量
             * @example null
             */
            chapter_count: number;
            /**
             * Format: ISODate
             * @description 创建时间
             * @example 2021-07-09T00:16:00.000Z
             */
            created_time: string;
            /**
             * Format: ISODate
             * @description 更新时间
             * @example 2021-07-09T00:16:00.000Z
             */
            updated_time: string;
            /** @description 根牌组<br><br>引用自：[MarkjiRootDeck](/schemas/MarkjiRootDeck) */
            root_deck?: components["schemas"]["MarkjiRootDeck"];
        };
        /** @description 暂无文档 */
        MarkjiChapterset: {
            /**
             * @description 章节集 OpenAPI ID
             * @example null
             */
            id: string;
            /**
             * @description 牌组 OpenAPI ID
             * @example null
             */
            deck_id: string;
            /**
             * @description 章节集版本
             * @example null
             */
            revision: number;
            /**
             * @description 章节 OpenAPI ID 列表
             * @example null
             */
            chapter_ids: string[];
            /**
             * Format: ISODate
             * @description 创建时间
             * @example 2021-07-09T00:16:00.000Z
             */
            created_time: string;
            /**
             * Format: ISODate
             * @description 更新时间
             * @example 2021-07-09T00:16:00.000Z
             */
            updated_time: string;
        };
        /** @description 暂无文档 */
        MarkjiChapter: {
            /**
             * @description 章节 OpenAPI ID
             * @example null
             */
            id: string;
            /**
             * @description 牌组 OpenAPI ID
             * @example null
             */
            deck_id: string;
            /**
             * @description 章节名称
             * @example null
             */
            name: string;
            /**
             * @description 章节版本
             * @example null
             */
            revision: number;
            /**
             * @description 卡片 OpenAPI ID 列表
             * @example null
             */
            card_ids: string[];
            /**
             * @description 用户 OpenAPI ID
             * @example null
             */
            creator: string;
            /**
             * Format: ISODate
             * @description 创建时间
             * @example 2021-07-09T00:16:00.000Z
             */
            created_time: string;
            /**
             * Format: ISODate
             * @description 更新时间
             * @example 2021-07-09T00:16:00.000Z
             */
            updated_time: string;
        };
        /** @description 暂无文档 */
        MarkjiCard: {
            /**
             * @description 卡片 OpenAPI ID
             * @example null
             */
            id: string;
            /** @description 卡片状态<br><br>引用自：[MarkjiStatus](/schemas/MarkjiStatus) */
            status: components["schemas"]["MarkjiStatus"];
            /**
             * @description 牌组 OpenAPI ID
             * @example null
             */
            deck_id: string;
            /**
             * @description 上游卡片 OpenAPI ID
             * @example null
             */
            parent_id?: string;
            /**
             * @description 根卡片 OpenAPI ID
             * @example null
             */
            root_id?: string;
            /**
             * @description 卡片版本
             * @example null
             */
            revision: number;
            /**
             * @description 卡片内容
             * @example null
             */
            content: string;
            /** @description 内容类型<br><br>引用自：[MarkjiContentType](/schemas/MarkjiContentType) */
            content_type: components["schemas"]["MarkjiContentType"];
            /** @description 卡片包含的文件<br><br>引用自：[MarkjiFile](/schemas/MarkjiFile) */
            files: components["schemas"]["MarkjiFile"][];
            /**
             * @description 用户 OpenAPI ID
             * @example null
             */
            creator: string;
            /** @description 卡片来源<br><br>引用自：[MarkjiSource](/schemas/MarkjiSource) */
            source: components["schemas"]["MarkjiSource"];
            /**
             * @description 语法版本
             * @example null
             */
            grammar_version: number;
            /**
             * @description 引用的根卡片 OpenAPI ID 列表
             * @example null
             */
            card_rids?: string[];
            /**
             * Format: ISODate
             * @description 创建时间
             * @example 2021-07-09T00:16:00.000Z
             */
            created_time: string;
            /**
             * Format: ISODate
             * @description 更新时间
             * @example 2021-07-09T00:16:00.000Z
             */
            updated_time: string;
        };
        /** @description 暂无文档 */
        MarkjiFolderItem: {
            /**
             * @description 对象 OpenAPI ID。object_class 为 DECK 时是牌组 ID，为 FOLDER 时是文件夹 ID
             * @example null
             */
            object_id: string;
            /** @description 对象类型<br><br>引用自：[MarkjiFolderItemClass](/schemas/MarkjiFolderItemClass) */
            object_class: components["schemas"]["MarkjiFolderItemClass"];
            /**
             * @description 排序值
             * @example null
             */
            order: number;
        };
        /** @description 暂无文档 */
        MarkjiFolder: {
            /**
             * @description 文件夹 OpenAPI ID
             * @example null
             */
            id: string;
            /** @description 文件夹内对象<br><br>引用自：[MarkjiFolderItem](/schemas/MarkjiFolderItem) */
            items: components["schemas"]["MarkjiFolderItem"][];
            /**
             * @description 父文件夹 OpenAPI ID
             * @example null
             */
            parent_id?: string;
            /**
             * @description 文件夹名称
             * @example null
             */
            name: string;
        };
        /** @description 暂无文档 */
        MarkjiFile: {
            /**
             * @description 文件 OpenAPI ID
             * @example null
             */
            id: string;
            /**
             * @description 文件访问地址
             * @example null
             */
            url: string;
            /**
             * @description MIME 类型
             * @example null
             */
            mime: string;
            /**
             * @description 文件大小，单位 KB，按 4KB 对齐
             * @example null
             */
            size: number;
            /**
             * @description 文件信息
             * @example null
             */
            info: Record<string, never>;
            /**
             * Format: ISODate
             * @description 文件访问地址过期时间
             * @example 2021-07-09T00:16:00.000Z
             */
            expire_time: string;
        };
        /**
         * @description 释义状态
         *
         *     - `PUBLISHED`: 发布
         *     - `UNPUBLISHED`: 未发布
         *     - `DELETED`: 删除
         * @enum {string}
         */
        InterpretationStatus: "PUBLISHED" | "UNPUBLISHED" | "DELETED";
        /** @description 释义 */
        Interpretation: {
            /**
             * @description id
             * @example 5a7BFf4F63612e5AD9fdebB7a50D3881
             */
            id: string;
            /**
             * @description 释义
             * @example n. 苹果
             */
            interpretation: string;
            /**
             * @description 标签
             * @example [
             *       "考研"
             *     ]
             */
            tags: string[];
            /** @description 状态
             *     @Example PUBLISHED<br><br>引用自：[InterpretationStatus](/schemas/InterpretationStatus) */
            status: components["schemas"]["InterpretationStatus"];
            /**
             * Format: ISODate
             * @description 创建时间
             *     ISO 8601 格式
             * @example 2023-03-13T16:00:00.000Z
             */
            created_time: string;
            /**
             * Format: ISODate
             * @description 更新时间
             *     ISO 8601 格式
             * @example 2023-03-13T16:00:00.000Z
             */
            updated_time: string;
        };
        /**
         * @description 助记状态
         *
         *     - `PUBLISHED`: 发布
         *     - `DELETED`: 删除
         * @enum {string}
         */
        NoteStatus: "PUBLISHED" | "DELETED";
        /** @description 助记 */
        Note: {
            /**
             * @description id
             * @example 5a7BFf4F63612e5AD9fdebB7a50D3881
             */
            id: string;
            /**
             * @description 类型
             * @example 谐音.
             */
            note_type: string;
            /**
             * @description 助记
             * @example apple
             */
            note: string;
            /** @description 状态
             *     @Example PUBLISHED<br><br>引用自：[NoteStatus](/schemas/NoteStatus) */
            status: components["schemas"]["NoteStatus"];
            /**
             * Format: ISODate
             * @description 创建时间
             *     ISO 8601 格式
             * @example 2023-03-13T16:00:00.000Z
             */
            created_time: string;
            /**
             * Format: ISODate
             * @description 更新时间
             *     ISO 8601 格式
             * @example 2023-03-13T16:00:00.000Z
             */
            updated_time: string;
        };
        /**
         * @description 云词本状态
         *
         *     - `PUBLISHED`: 发布
         *     - `UNPUBLISHED`: 未发布
         *     - `DELETED`: 删除
         * @enum {string}
         */
        NotepadStatus: "PUBLISHED" | "UNPUBLISHED" | "DELETED";
        /**
         * @description 云词本类型
         *
         *     - `FAVORITE`: 我的收藏
         *     - `NOTEPAD`: 云词本
         * @enum {string}
         */
        NotepadType: "FAVORITE" | "NOTEPAD";
        /** @description 云词本解析结果 */
        NotepadParsedItem: {
            /**
             * @description 类型
             * @example CHAPTER
             * @enum {string}
             */
            type: "CHAPTER" | "WORD";
            /** @description 数据 */
            data: {
                /**
                 * @description 章节
                 * @example 我的章节
                 */
                chapter: string;
                /**
                 * @description 单词
                 *     当 type=WORD 时，该字段才有值
                 * @example apple
                 */
                word?: string;
            };
        };
        /** @description 云词本 */
        Notepad: {
            /**
             * @description id
             * @example 5a7BFf4F63612e5AD9fdebB7a50D3881
             */
            id: string;
            /** @description 类型
             *     @Example NOTEPAD<br><br>引用自：[NotepadType](/schemas/NotepadType) */
            type: components["schemas"]["NotepadType"];
            /**
             * @description 创建者 id
             * @example 192
             */
            creator: number;
            /** @description 状态
             *     @Example PUBLISHED<br><br>引用自：[NotepadStatus](/schemas/NotepadStatus) */
            status: components["schemas"]["NotepadStatus"];
            /**
             * @description 内容
             *     - 章节模式：以 `#` 开头，井号后是章节名称，下方是该章节的单词列表，一行一个
             *     - 文本模式：不以 `#` 开头，不限格式，会识别尽量多的单词和短语，开头添加 `//` 则还原单词原型后再提取
             *
             * @example apple
             */
            content: string;
            /**
             * @description 标题
             * @example 常用词汇
             */
            title: string;
            /**
             * @description 简介
             * @example 常用
             */
            brief: string;
            /**
             * @description 标签
             * @example [
             *       "考研"
             *     ]
             */
            tags: string[];
            /** @description 解析结果<br><br>引用自：[NotepadParsedItem](/schemas/NotepadParsedItem) */
            list: components["schemas"]["NotepadParsedItem"][];
            /**
             * Format: ISODate
             * @description 创建时间
             *     ISO 8601 格式
             * @example 2023-03-13T16:00:00.000Z
             */
            created_time: string;
            /**
             * Format: ISODate
             * @description 更新时间
             *     ISO 8601 格式
             * @example 2023-03-13T16:00:00.000Z
             */
            updated_time: string;
        };
        /** @description 简要云词本 */
        BriefNotepad: {
            /**
             * @description id
             * @example 5a7BFf4F63612e5AD9fdebB7a50D3881
             */
            id: string;
            /** @description 类型
             *     @Example NOTEPAD<br><br>引用自：[NotepadType](/schemas/NotepadType) */
            type: components["schemas"]["NotepadType"];
            /**
             * @description 创建者 id
             * @example 192
             */
            creator: number;
            /** @description 状态
             *     @Example PUBLISHED<br><br>引用自：[NotepadStatus](/schemas/NotepadStatus) */
            status: components["schemas"]["NotepadStatus"];
            /**
             * @description 标题
             * @example 常用词汇
             */
            title: string;
            /**
             * @description 简介
             * @example 常用
             */
            brief: string;
            /**
             * @description 标签
             * @example [
             *       "考研"
             *     ]
             */
            tags: string[];
            /**
             * Format: ISODate
             * @description 创建时间
             *     ISO 8601 格式
             * @example 2023-03-13T16:00:00.000Z
             */
            created_time: string;
            /**
             * Format: ISODate
             * @description 更新时间
             *     ISO 8601 格式
             * @example 2023-03-13T16:00:00.000Z
             */
            updated_time: string;
        };
        /**
         * @description 例句状态
         *
         *     - `PUBLISHED`: 发布
         *     - `DELETED`: 删除
         * @enum {string}
         */
        PhraseStatus: "PUBLISHED" | "DELETED";
        /** @description 例句中的单词高亮区间
         *     [start, end) */
        PhraseHighlightRange: {
            /**
             * @description 高亮起始位置
             * @example 1
             */
            start: number;
            /**
             * @description 高亮结束位置（不包含）
             * @example 10
             */
            end: number;
        };
        /** @description 例句 */
        Phrase: {
            /**
             * @description id
             * @example 5a7BFf4F63612e5AD9fdebB7a50D3881
             */
            id: string;
            /**
             * @description 例句
             * @example This is an apple.
             */
            phrase: string;
            /**
             * @description 翻译
             * @example 这是一个苹果。
             */
            interpretation: string;
            /**
             * @description 标签
             * @example [
             *       "考研"
             *     ]
             */
            tags: string[];
            /** @description 例句中的单词高亮区间
             *     实际返回的数据是二维数组<br><br>引用自：[PhraseHighlightRange](/schemas/PhraseHighlightRange) */
            highlight: components["schemas"]["PhraseHighlightRange"][];
            /** @description 状态
             *     @Example PUBLISHED<br><br>引用自：[PhraseStatus](/schemas/PhraseStatus) */
            status: components["schemas"]["PhraseStatus"];
            /**
             * Format: ISODate
             * @description 创建时间
             *     ISO 8601 格式
             * @example 2023-03-13T16:00:00.000Z
             */
            created_time: string;
            /**
             * Format: ISODate
             * @description 更新时间
             *     ISO 8601 格式
             * @example 2023-03-13T16:00:00.000Z
             */
            updated_time: string;
            /**
             * @description 来源
             * @example 考研
             */
            origin: string;
        };
        /**
         * @description
         *
         *     - `FAMILIAR`: 认识
         *     - `VAGUE`: 模糊
         *     - `FORGET`: 忘记
         *     - `WELL_FAMILIAR`: 熟知
         *     - `CANCEL_WELL_FAMILIAR`: 取消熟知
         * @enum {string}
         */
        StudyResponse: "FAMILIAR" | "VAGUE" | "FORGET" | "WELL_FAMILIAR" | "CANCEL_WELL_FAMILIAR";
        /** @description 暂无文档 */
        StudyProgress: {
            /**
             * @description 已完成的单词数
             * @example 10
             */
            finished: number;
            /**
             * @description 今日应完成的单词数
             * @example 20
             */
            total: number;
            /**
             * @description 今日学习时长，毫秒
             * @example 114514
             */
            study_time: number;
        };
        /** @description 今日学习单词 */
        StudyTodayItem: {
            /**
             * @description 单词 ID
             * @example vocid
             */
            voc_id: string;
            /**
             * @description 单词拼写
             * @example apple
             */
            voc_spelling: string;
            /**
             * @description 学习顺序
             * @example 1
             */
            order: number;
            /** @description 当天第一次反馈<br><br>引用自：[StudyResponse](/schemas/StudyResponse) */
            first_response?: components["schemas"]["StudyResponse"];
            /**
             * @description 是否是新学单词
             * @example false
             */
            is_new: boolean;
            /**
             * @description 是否已完成当日学习
             * @example false
             */
            is_finished: boolean;
        };
        /** @description 学习记录 */
        StudyRecord: {
            /**
             * @description 单词 ID
             * @example vocid
             */
            voc_id: string;
            /**
             * @description 单词拼写
             * @example apple
             */
            voc_spelling: string;
            /**
             * Format: ISODate
             * @description 添加日期
             * @example 2021-07-09T00:16:00.000Z
             */
            add_date: string;
            /**
             * Format: ISODate
             * @description 首次学习日期
             * @example 2021-07-09T00:16:00.000Z
             */
            first_study_date?: string;
            /**
             * Format: ISODate
             * @description 上次学习日期
             * @example 2021-07-09T00:16:00.000Z
             */
            last_study_date?: string;
            /**
             * Format: ISODate
             * @description 下次学习日期
             * @example 2021-07-09T00:16:00.000Z
             */
            next_study_date?: string;
            /** @description 上次反馈<br><br>引用自：[StudyResponse](/schemas/StudyResponse) */
            last_response?: components["schemas"]["StudyResponse"];
            /**
             * @description 学习次数（每日最多计入 1 次）
             * @example 10
             */
            study_count: number;
            /**
             * @description 标签
             * @enum {string}
             */
            tags: "STICKING" | "WELL_FAMILIAR";
        };
        /** @description 暂无文档 */
        Vocabulary: {
            /**
             * @description id
             * @example 5a7BFf4F63612e5AD9fdebB7a50D3881
             */
            id: string;
            /**
             * @description 拼写
             * @example apple
             */
            spelling: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "maimemo.openapi.markji.v1.MarkjiContentService.ListFolders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "*/*"?: never;
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description <br><br>引用自：[MarkjiFolder](/schemas/MarkjiFolder) */
                        folders: components["schemas"]["MarkjiFolder"][];
                    };
                };
            };
        };
    };
    "maimemo.openapi.markji.v1.MarkjiContentService.ListDecks": {
        parameters: {
            query?: {
                /** @description 偏移量 */
                offset?: number;
                /** @description 每页数量 */
                limit?: number;
                /** @description 文件夹 OpenAPI ID */
                folder_id?: string;
                /** @description 牌组来源<br><br>引用自：[MarkjiSource](/schemas/MarkjiSource) */
                source?: components["schemas"]["MarkjiSource"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "*/*"?: never;
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description <br><br>引用自：[MarkjiDeck](/schemas/MarkjiDeck) */
                        decks: components["schemas"]["MarkjiDeck"][];
                        /**
                         * @description 总数
                         * @example null
                         */
                        total: number;
                    };
                };
            };
        };
    };
    "maimemo.openapi.markji.v1.MarkjiContentService.GetDeck": {
        parameters: {
            query?: {
                /** @description 是否返回根牌组信息 */
                with_root?: boolean;
            };
            header?: never;
            path: {
                /** @description 牌组 OpenAPI ID */
                deck: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "*/*"?: never;
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description null<br><br>引用自：[MarkjiDeck](/schemas/MarkjiDeck) */
                        deck: components["schemas"]["MarkjiDeck"];
                    };
                };
            };
        };
    };
    "maimemo.openapi.markji.v1.MarkjiContentService.ListChapters": {
        parameters: {
            query?: {
                /** @description 只返回更新时间晚于该时间的章节 */
                updated_time?: string;
                /** @description 是否同时返回章节内卡片 */
                with_cards?: boolean;
            };
            header?: never;
            path: {
                /** @description 牌组 OpenAPI ID */
                deck: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "*/*"?: never;
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description null<br><br>引用自：[MarkjiChapterset](/schemas/MarkjiChapterset) */
                        chapterset?: components["schemas"]["MarkjiChapterset"];
                        /** @description <br><br>引用自：[MarkjiChapter](/schemas/MarkjiChapter) */
                        chapters: components["schemas"]["MarkjiChapter"][];
                        /** @description <br><br>引用自：[MarkjiCard](/schemas/MarkjiCard) */
                        cards?: components["schemas"]["MarkjiCard"][];
                    };
                };
            };
        };
    };
    "maimemo.openapi.markji.v1.MarkjiContentService.GetChapter": {
        parameters: {
            query?: {
                /** @description 是否同时返回章节内卡片 */
                with_cards?: boolean;
                /** @description 只返回更新时间晚于该时间的章节 */
                updated_time?: string;
            };
            header?: never;
            path: {
                /** @description 牌组 OpenAPI ID */
                deck: string;
                /** @description 章节 OpenAPI ID */
                chapter: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "*/*"?: never;
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description null<br><br>引用自：[MarkjiChapterset](/schemas/MarkjiChapterset) */
                        chapterset?: components["schemas"]["MarkjiChapterset"];
                        /** @description null<br><br>引用自：[MarkjiChapter](/schemas/MarkjiChapter) */
                        chapter?: components["schemas"]["MarkjiChapter"];
                        /** @description <br><br>引用自：[MarkjiCard](/schemas/MarkjiCard) */
                        cards?: components["schemas"]["MarkjiCard"][];
                    };
                };
            };
        };
    };
    "maimemo.openapi.markji.v1.MarkjiContentService.GetCard": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 牌组 OpenAPI ID */
                deck: string;
                /** @description 卡片 OpenAPI ID */
                card: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "*/*"?: never;
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description null<br><br>引用自：[MarkjiCard](/schemas/MarkjiCard) */
                        card: components["schemas"]["MarkjiCard"];
                    };
                };
            };
        };
    };
    "maimemo.openapi.markji.v1.MarkjiContentService.CreateCard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * @description 牌组 OpenAPI ID
                     * @example null
                     */
                    deck: string;
                    /**
                     * @description 章节 OpenAPI ID
                     * @example null
                     */
                    chapter: string;
                    card: {
                        /**
                         * @description 卡片内容
                         * @example null
                         */
                        content: string;
                        /**
                         * @description 语法版本
                         * @example null
                         */
                        grammar_version: number;
                    };
                    /**
                     * @description 插入位置，不传则追加到章节末尾
                     * @example null
                     */
                    order?: number;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description null<br><br>引用自：[MarkjiCard](/schemas/MarkjiCard) */
                        card: components["schemas"]["MarkjiCard"];
                        /** @description null<br><br>引用自：[MarkjiChapter](/schemas/MarkjiChapter) */
                        chapter: components["schemas"]["MarkjiChapter"];
                    };
                };
            };
        };
    };
    "maimemo.openapi.markji.v1.MarkjiContentService.UpdateCard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * @description 要更新的牌组 ID
                     * @example null
                     */
                    deck_id: string;
                    /**
                     * @description 要更新的卡片 ID
                     * @example null
                     */
                    card_id: string;
                    card: {
                        /**
                         * @description 卡片内容
                         * @example null
                         */
                        content: string;
                        /**
                         * @description 语法版本
                         * @example null
                         */
                        grammar_version: number;
                    };
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description null<br><br>引用自：[MarkjiCard](/schemas/MarkjiCard) */
                        card: components["schemas"]["MarkjiCard"];
                    };
                };
            };
        };
    };
    "maimemo.openapi.markji.v1.MarkjiContentService.UploadFile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * @description 可选，牌组 OpenAPI ID，指定后按牌组编辑权限归属文件
                     * @example null
                     */
                    deck_id?: string;
                    /**
                     * @description multipart/form-data 中的文件字段，字段名为 `file`
                     * @example null
                     */
                    file: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description null<br><br>引用自：[MarkjiFile](/schemas/MarkjiFile) */
                        file: components["schemas"]["MarkjiFile"];
                    };
                };
            };
        };
    };
    "maimemo.openapi.markji.v1.MarkjiContentService.QueryFiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * @description 文件 OpenAPI ID 列表
                     * @example null
                     */
                    ids: string[];
                    /**
                     * @description 文件外链有效期，默认 30 天，单位秒
                     * @example null
                     */
                    expires?: number;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description <br><br>引用自：[MarkjiFile](/schemas/MarkjiFile) */
                        files: components["schemas"]["MarkjiFile"][];
                    };
                };
            };
        };
    };
    "maimemo.openapi.memo.interpretation.v1.InterpretationService.ListInterpretations": {
        parameters: {
            query: {
                /** @description 单词 id */
                voc_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "*/*"?: never;
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description 释义列表<br><br>引用自：[Interpretation](/schemas/Interpretation) */
                        interpretations: components["schemas"]["Interpretation"][];
                    };
                };
            };
        };
    };
    "maimemo.openapi.memo.interpretation.v1.InterpretationService.CreateInterpretation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    interpretation: {
                        /**
                         * @description 单词 id
                         * @example 5a7BFf4F63612e5AD9fdebB7a50D3881
                         */
                        voc_id: string;
                        /**
                         * @description 释义
                         * @example n. 苹果
                         */
                        interpretation: string;
                        /**
                         * @description 标签
                         * @example [
                         *       "考研"
                         *     ]
                         */
                        tags: string[];
                        /** @description 状态
                         *     @Example PUBLISHED<br><br>引用自：[InterpretationStatus](/schemas/InterpretationStatus) */
                        status: components["schemas"]["InterpretationStatus"];
                    };
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description 释义<br><br>引用自：[Interpretation](/schemas/Interpretation) */
                        interpretation: components["schemas"]["Interpretation"];
                    };
                };
            };
        };
    };
    "maimemo.openapi.memo.interpretation.v1.InterpretationService.UpdateInterpretation": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 释义 id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    interpretation: {
                        /**
                         * @description 释义
                         * @example n. 苹果
                         */
                        interpretation: string;
                        /**
                         * @description 标签
                         * @example [
                         *       "考研"
                         *     ]
                         */
                        tags: string[];
                        /** @description 状态
                         *     @Example PUBLISHED<br><br>引用自：[InterpretationStatus](/schemas/InterpretationStatus) */
                        status: components["schemas"]["InterpretationStatus"];
                    };
                    /**
                     * @description 释义 id
                     * @example 5a7BFf4F63612e5AD9fdebB7a50D3881
                     */
                    id: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description 释义<br><br>引用自：[Interpretation](/schemas/Interpretation) */
                        interpretation: components["schemas"]["Interpretation"];
                    };
                };
            };
        };
    };
    "maimemo.openapi.memo.interpretation.v1.InterpretationService.DeleteInterpretation": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 释义 id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "*/*"?: never;
            };
        };
        responses: never;
    };
    "maimemo.openapi.memo.note.v1.NoteService.ListNotes": {
        parameters: {
            query: {
                /** @description 单词 id */
                voc_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "*/*"?: never;
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description 助记列表<br><br>引用自：[Note](/schemas/Note) */
                        notes: components["schemas"]["Note"][];
                    };
                };
            };
        };
    };
    "maimemo.openapi.memo.note.v1.NoteService.CreateNote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    note: {
                        /**
                         * @description 单词 id
                         * @example 5a7BFf4F63612e5AD9fdebB7a50D3881
                         */
                        voc_id: string;
                        /**
                         * @description 类型
                         * @example 谐音.
                         */
                        note_type: string;
                        /**
                         * @description 助记
                         * @example apple
                         */
                        note: string;
                    };
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description 助记<br><br>引用自：[Note](/schemas/Note) */
                        note: components["schemas"]["Note"];
                    };
                };
            };
        };
    };
    "maimemo.openapi.memo.note.v1.NoteService.UpdateNote": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 助记 id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * @description 要更新的助记 ID
                     * @example null
                     */
                    id: string;
                    note: {
                        /**
                         * @description 类型
                         * @example 谐音.
                         */
                        note_type: string;
                        /**
                         * @description 助记
                         * @example apple
                         */
                        note: string;
                    };
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description 助记<br><br>引用自：[Note](/schemas/Note) */
                        note: components["schemas"]["Note"];
                    };
                };
            };
        };
    };
    "maimemo.openapi.memo.note.v1.NoteService.DeleteNote": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 助记 id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "*/*"?: never;
            };
        };
        responses: never;
    };
    "maimemo.openapi.memo.notepad.v1.NotepadService.ListNotepads": {
        parameters: {
            query?: {
                /** @description 查询数量 */
                limit?: number;
                /** @description 查询跳过 */
                offset?: number;
                /** @description 词本 id 列表 */
                ids?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "*/*"?: never;
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description 云词本列表<br><br>引用自：[BriefNotepad](/schemas/BriefNotepad) */
                        notepads: components["schemas"]["BriefNotepad"][];
                    };
                };
            };
        };
    };
    "maimemo.openapi.memo.notepad.v1.NotepadService.CreateNotepad": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description 创建数据 */
                    notepad: {
                        /** @description 状态
                         *     @Example PUBLISHED<br><br>引用自：[NotepadStatus](/schemas/NotepadStatus) */
                        status: components["schemas"]["NotepadStatus"];
                        /**
                         * @description 内容
                         * @example apple
                         */
                        content: string;
                        /**
                         * @description 标题
                         * @example 常用词汇
                         */
                        title: string;
                        /**
                         * @description 简介
                         * @example 常用
                         */
                        brief: string;
                        /**
                         * @description 标签
                         * @example [
                         *       "考研"
                         *     ]
                         */
                        tags: string[];
                    };
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description 云词本<br><br>引用自：[Notepad](/schemas/Notepad) */
                        notepad: components["schemas"]["Notepad"];
                    };
                };
            };
        };
    };
    "maimemo.openapi.memo.notepad.v1.NotepadService.GetNotepad": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 云词本 id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "*/*"?: never;
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description 云词本<br><br>引用自：[Notepad](/schemas/Notepad) */
                        notepad: components["schemas"]["Notepad"];
                    };
                };
            };
        };
    };
    "maimemo.openapi.memo.notepad.v1.NotepadService.UpdateNotepad": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 云词本 id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description 更新数据 */
                    notepad: {
                        /** @description 状态
                         *     @Example PUBLISHED<br><br>引用自：[NotepadStatus](/schemas/NotepadStatus) */
                        status: components["schemas"]["NotepadStatus"];
                        /**
                         * @description 内容
                         * @example apple
                         */
                        content: string;
                        /**
                         * @description 标题
                         * @example 常用词汇
                         */
                        title: string;
                        /**
                         * @description 简介
                         * @example 常用
                         */
                        brief: string;
                        /**
                         * @description 标签
                         * @example [
                         *       "考研"
                         *     ]
                         */
                        tags: string[];
                    };
                    /**
                     * @description 云词本 id
                     * @example 5a7BFf4F63612e5AD9fdebB7a50D3881
                     */
                    id: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description 云词本<br><br>引用自：[Notepad](/schemas/Notepad) */
                        notepad: components["schemas"]["Notepad"];
                    };
                };
            };
        };
    };
    "maimemo.openapi.memo.notepad.v1.NotepadService.DeleteNotepad": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 云词本 id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "*/*"?: never;
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description 云词本<br><br>引用自：[Notepad](/schemas/Notepad) */
                        notepad: components["schemas"]["Notepad"];
                    };
                };
            };
        };
    };
    "maimemo.openapi.memo.phrase.v1.PhraseService.ListPhrases": {
        parameters: {
            query: {
                /** @description 单词 id */
                voc_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "*/*"?: never;
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description 例句列表<br><br>引用自：[Phrase](/schemas/Phrase) */
                        phrases: components["schemas"]["Phrase"][];
                    };
                };
            };
        };
    };
    "maimemo.openapi.memo.phrase.v1.PhraseService.CreatePhrase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    phrase: {
                        /**
                         * @description 单词 id
                         * @example 5a7BFf4F63612e5AD9fdebB7a50D3881
                         */
                        voc_id: string;
                        /**
                         * @description 例句
                         * @example This is an apple.
                         */
                        phrase: string;
                        /**
                         * @description 翻译
                         * @example 这是一个苹果。
                         */
                        interpretation: string;
                        /**
                         * @description 标签
                         * @example [
                         *       "考研"
                         *     ]
                         */
                        tags: string[];
                        /**
                         * @description 来源
                         * @example 考研
                         */
                        origin: string;
                    };
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description 例句<br><br>引用自：[Phrase](/schemas/Phrase) */
                        phrase: components["schemas"]["Phrase"];
                    };
                };
            };
        };
    };
    "maimemo.openapi.memo.phrase.v1.PhraseService.UpdatePhrase": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 例句 id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    phrase: {
                        /**
                         * @description 例句
                         * @example This is an apple.
                         */
                        phrase: string;
                        /**
                         * @description 翻译
                         * @example 这是一个苹果。
                         */
                        interpretation: string;
                        /**
                         * @description 标签
                         * @example [
                         *       "考研"
                         *     ]
                         */
                        tags: string[];
                        /**
                         * @description 来源
                         * @example 考研
                         */
                        origin: string;
                    };
                    /**
                     * @description 例句 id
                     * @example 5a7BFf4F63612e5AD9fdebB7a50D3881
                     */
                    id: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description 例句<br><br>引用自：[Phrase](/schemas/Phrase) */
                        phrase: components["schemas"]["Phrase"];
                    };
                };
            };
        };
    };
    "maimemo.openapi.memo.phrase.v1.PhraseService.DeletePhrase": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 例句 id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "*/*"?: never;
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description 例句<br><br>引用自：[Phrase](/schemas/Phrase) */
                        phrase: components["schemas"]["Phrase"];
                    };
                };
            };
        };
    };
    "maimemo.openapi.memo.study.v1.StudyService.GetStudyProgress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "*/*"?: never;
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description 学习进度及时长<br><br>引用自：[StudyProgress](/schemas/StudyProgress) */
                        progress: components["schemas"]["StudyProgress"];
                    };
                };
            };
        };
    };
    "maimemo.openapi.memo.study.v1.StudyService.GetTodayItems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * @description 筛选是否已完成
                     * @example false
                     */
                    is_finished?: boolean;
                    /**
                     * @description 筛选是否新学单词
                     * @example false
                     */
                    is_new?: boolean;
                    /**
                     * @description 根据单词 ID 列表查询，最多 1000，忽略其他条件
                     * @example [
                     *       "id1",
                     *       "id2"
                     *     ]
                     */
                    voc_ids?: string[];
                    /**
                     * @description 根据单词拼写列表查询，最多 1000，忽略其他条件，不可与 voc_ids 同时使用
                     * @example [
                     *       "hello",
                     *       "world"
                     *     ]
                     */
                    spellings?: string[];
                    /**
                     * @description 最多根据学习顺序获取前 1000 条数据，默认 50
                     * @example 50
                     */
                    limit?: number;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description 今日学习列表<br><br>引用自：[StudyTodayItem](/schemas/StudyTodayItem) */
                        today_items: components["schemas"]["StudyTodayItem"][];
                    };
                };
            };
        };
    };
    "maimemo.openapi.memo.study.v1.StudyService.QueryStudyRecords": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description 根据下次学习日期筛选 */
                    next_study_date?: {
                        /**
                         * Format: ISODate
                         * @description 大于等于时间，北京时区
                         * @example 2021-07-09T00:16:00.000Z
                         */
                        start?: string;
                        /**
                         * Format: ISODate
                         * @description 小于等于时间，北京时区
                         * @example 2021-07-09T00:16:00.000Z
                         */
                        end?: string;
                    };
                    /**
                     * @description 根据单词 ID 筛选，忽略其他条件
                     * @example [
                     *       "id1",
                     *       "id2"
                     *     ]
                     */
                    voc_ids?: string[];
                    /**
                     * @description 根据单词拼写列表查询，最多 1000，忽略其他条件，不可与 voc_ids 同时使用
                     * @example [
                     *       "hello",
                     *       "world"
                     *     ]
                     */
                    spellings?: string[];
                    /**
                     * @description 仅计算结果总数，不返回数据列表
                     * @example false
                     */
                    as_count?: boolean;
                    /**
                     * @description 最多根据下次学习日期获取前 1000 条数据，默认 50
                     * @example 50
                     */
                    limit?: number;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description `as_count=true` 时为空<br><br>引用自：[StudyRecord](/schemas/StudyRecord) */
                        records: components["schemas"]["StudyRecord"][];
                        /**
                         * @description `as_count=true` 时有效
                         * @example 114514
                         */
                        count: number;
                    };
                };
            };
        };
    };
    "maimemo.openapi.memo.study.v1.StudyService.AddWords": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description 单词列表，最多一次添加 1000 个单词 */
                    words: {
                        /**
                         * @description 单词 ID，通过查询单词接口获取
                         * @example id1
                         */
                        id: string;
                    }[];
                    /**
                     * @description 是否一并提前复习，无等级限制
                     * @example false
                     */
                    advance: boolean;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description 成功添加的数量，单词上限不足或者已经添加过会影响成功添加的数量
                         * @example 114
                         */
                        added_count: number;
                    };
                };
            };
        };
    };
    "maimemo.openapi.memo.study.v1.StudyService.AdvanceStudy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @example [
                     *       "id1",
                     *       "id2"
                     *     ] */
                    voc_ids: string[];
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description 成功提前的数量，单词未加入会影响成功提前的数量
                         * @example 514
                         */
                        advanced_count: number;
                    };
                };
            };
        };
    };
    "maimemo.openapi.memo.vocabulary.v1.VocabularyService.GetVocabulary": {
        parameters: {
            query: {
                /** @description 单词拼写 */
                spelling: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "*/*"?: never;
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description 单词<br><br>引用自：[Vocabulary](/schemas/Vocabulary) */
                        voc: components["schemas"]["Vocabulary"];
                    };
                };
            };
        };
    };
    "maimemo.openapi.memo.vocabulary.v1.VocabularyService.ListVocabulary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * @description 根据拼写查询，最多 1000
                     * @example null
                     */
                    spellings?: string[];
                    /**
                     * @description 根据 id 查询，最多 1000
                     * @example null
                     */
                    ids?: string[];
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description <br><br>引用自：[Vocabulary](/schemas/Vocabulary) */
                        voc: components["schemas"]["Vocabulary"][];
                    };
                };
            };
        };
    };
}
